name: Publish Fuel Cost Desktop

on:
  push:
    tags:
      - '*'
jobs:
  publish_artifacts:
    env:
      PUBLISH_DIR: publish
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
        mode: [release]
        include:
          - os: ubuntu-20.04
            subcommand: linux
            setup_desktop_script: .github/scripts/setup_on_linux.sh
            prepare_to_pack_script: .github/scripts/prepare_to_pack_for_linux.sh
            distribution_path: build/linux/x64/release
          #- os: windows-2019
          #  subcommand: windows
          #  setup_desktop_script: .github/scripts/setup_on_windows.sh
          #  prepare_to_pack_script: .github/scripts/prepare_to_pack_for_windows.sh
          #  distribution_path: build/windows/runner/Release
          - os: macos-11
            subcommand: macos
            setup_desktop_script: .github/scripts/setup_on_macos.sh
            prepare_to_pack_script: .github/scripts/prepare_to_pack_for_macos.sh
            distribution_path: build/macos/Build/Products/release

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: setup flutter channel
        run: .github/scripts/setup_flutter_channel.sh
      - name: setup flutter desktop
        shell: bash
        run: ${{ matrix.setup_desktop_script }}
      - name: doctor
        run: flutter doctor -v
      - name: install dependencies
        run: flutter pub get
      - name: build
        run: flutter build ${{ matrix.subcommand }} --${{ matrix.mode }}
      - name: prepare to pack
        shell: bash
        run: ${{ matrix.prepare_to_pack_script }}

      - name: output build info
        shell: bash
        run: .github/scripts/output_build_info.sh ${{ matrix.distribution_path }}

      - name: compress files (Windows)
        if: runner.os == 'Windows'
        run: |-
          mkdir -p ${{ env.PUBLISH_DIR }}
          cd ${{ matrix.distribution_path }}
          powershell Compress-Archive -Path ./* -DestinationPath $Env:GITHUB_WORKSPACE/${{ env.PUBLISH_DIR }}/FuelCost-${{ runner.os }}.zip
      - name: compress files (macOS, Linux)
        if: runner.os == 'macOS' || runner.os == 'Linux'
        run: |-
          mkdir -p ${{ env.PUBLISH_DIR }}
          cd ${{ matrix.distribution_path }}
          zip -r $GITHUB_WORKSPACE/${{ env.PUBLISH_DIR }}/pedax-${{ runner.os }}.zip .
      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          tag_name: ${{ github.event.inputs.tag }}
          files: ${{ env.PUBLISH_DIR }}/pedax-${{ runner.os }}.zip
